export const STUDENTS = [
	{
		'matric-number': '021-0101-0054',
		name: 'Ikumapayi Olamilekan John',
		session: '2023/2024',
		faculty: 'Science',
		department: 'Computer Science',
		level: '300 Level',
		semester: 'Second',
		gender: 'male',
		fees: [
			{
				name: 'School Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'Faculty Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'French Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'Medical Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
		],
		isCleared: true,
		attendance: [
			{ course: 'CSC 307', sessions: 30, attended: 28 },
			{ course: 'CSC 304', sessions: 18, attended: 18 },
			{ course: 'GST 200', sessions: 22, attended: 20 },
		],
		image: 'https://github.com/shadcn.png',
	},
	{
		'matric-number': '021-0101-0055',
		name: 'Doe Jane Emily',
		session: '2023/2024',
		faculty: 'Engineering',
		department: 'Mechanical Engineering',
		level: '200 Level',
		semester: 'First',
		gender: 'female',
		fees: [
			{
				name: 'School Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'Faculty Fees',
				isPaid: false,
				accountCheck: false,
				deanCheck: false,
				diaCheck: false,
				dvcCheck: false,
			},
			{
				name: 'French Fees',
				isPaid: false,
				accountCheck: false,
				deanCheck: false,
				diaCheck: false,
				dvcCheck: false,
			},
			{
				name: 'Medical Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
		],
		isCleared: false,
		attendance: [
			{ course: 'ENG 210', sessions: 25, attended: 22 },
			{ course: 'MTH 205', sessions: 20, attended: 15 },
			{ course: 'GST 200', sessions: 22, attended: 18 },
		],
		image: 'https://github.com/shadcn.png',
	},
	{
		'matric-number': '021-0101-0056',
		name: 'Maxwell Thompson Eric',
		session: '2023/2024',
		faculty: 'Arts',
		department: 'English Language',
		level: '400 Level',
		semester: 'Second',
		gender: 'male',
		fees: [
			{
				name: 'School Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'Faculty Fees',
				isPaid: true,
				accountCheck: true,
				deanCheck: true,
				diaCheck: true,
				dvcCheck: true,
			},
			{
				name: 'French Fees',
				isPaid: false,
				accountCheck: false,
				deanCheck: false,
				diaCheck: false,
				dvcCheck: false,
			},
			{
				name: 'Medical Fees',
				isPaid: false,
				accountCheck: false,
				deanCheck: false,
				diaCheck: false,
				dvcCheck: false,
			},
		],
		isCleared: false,
		attendance: [
			{ course: 'ENG 450', sessions: 30, attended: 27 },
			{ course: 'LIN 401', sessions: 24, attended: 24 },
			{ course: 'GST 200', sessions: 22, attended: 22 },
		],
		image: 'https://github.com/shadcn.png',
	},
];
